### ISSUE TITLE
local queue for a remote cups server (ipp) and kerberos

### ISSUE THREAD

**Issue by kenshin33** [apple/cups#5233]
Hi again, I mentioned that in #5203 that linux clients had no problems printing to a remote  cups server using kerberos Authentication, turns out that was false !!!!
using clien.conf works but adding a local queue (lpadmin - x printer -E -v ipp://remoteserver/priunters/print -m raw -o auth-info-required=negotiate) does not (it yields the same result as with OSX the job is held waiting fot authentication).
As you mentionned that the ipp backend should be run as the user requesting the job, I went and started reading  backend/ipp.c and sure enough there's a seteuid() call early on. even sop still no printing.
ther server ask for authentication and it stops there,  the client just gives up.

Runin directly the backend as the user requesting the print  job works (as in the user is authenticated as he should on the server.)  
Using execsnoop from bcc-tools, shows that the ipp backend is a child of cups-exec. which is called with -u 7 (UID of lp on my system)  running again with the uid of the user requesting the jobs works (in the sens that the user is authenticated as he should ).
So I decided to strace cupsd ans see what's going on,  in the child process for ipp it tries to find a credential cache for user lp. 

It seems to that the authentication doesn't work b/c cups-exec is called with -u 7. 

 the other problem is the location of the credential cache, what worked was the KEYRING type.  FILE as is the default on debian 8/9 was problematic, but that's an other story.

**Comment by michaelrsweet** [comment]
The IPP backend should be getting run as root, unless Debian has changed that. What does the following command report?

    ls -l /usr/lib/cups/backend

**Comment by kenshin33** [comment]
it looks like this:
    
    ls -l /usr/lib/cups/backend
    total 608
    -rwxr-xr-x 1 root root  10232 Jan 19  2017 beh                                                                                                                                     
    -rwxr--r-- 3 root root  18424 Jan 31  2017 dnssd                                                                                                                                   
    -rwxr--r-- 1 root root 227808 Feb 16  2016 gutenprint52+usb                                                                                                                        
    lrwxrwxrwx 1 root root      3 Jan 31  2017 http -> ipp                                                                                                                             
    lrwxrwxrwx 1 root root      3 Jan 31  2017 https -> ipp
    -rwxr-xr-x 1 root root  14336 Jan 19  2017 implicitclass
    -rwxr-xr-x 1 root root  75864 Jan 31  2017 ipp
    -rwxr-xr-x 1 root root  51296 Jan 31  2017 ipp14
    lrwxrwxrwx 1 root root      3 Jan 31  2017 ipps -> ipp
    -rwxr--r-- 2 root root  47192 Jan 31  2017 lpd
    -rwxr--r-- 3 root root  18424 Jan 31  2017 mdns
    -rwxr-xr-x 1 root root  18424 Jan 19  2017 parallel
    -rwx------ 1 root root  14328 Jan 19  2017 serial
    lrwxrwxrwx 1 root root     21 Nov 20 17:24 smb -> ../../../bin/smbspool
    -r-xr-xr-x 2 root root  26624 Jan 31  2017 snmp
    -r-xr-xr-x 2 root root  39000 Jan 31  2017 socket
    -r-xr--r-- 2 root root  34808 Jan 31  2017 usb
 here is the relevant output of strace:
      
    cupds.3090:execve("/usr/lib/cups/daemon/cups-exec", ["/usr/lib/cups/daemon/cups-exec", "-g", "7", "-n", "0", "-u", "7", "none", "/usr/lib/cups/backend/ipps", "ipps://HOSTNAME/"..., "16", "USER", "Untitled", "1", "media=Letter sides=one-sided num"...], [/* 34 vars */]) = 0
     ......
    cupds.3090:execve("/usr/lib/cups/backend/ipps", ["ipps://HOSTNAME"..., "16", "USER", "Untitled", "1", "media=Letter sides=one-sided num"...], [/* 34 vars */]) = 0
     .....
    cupds.3090:open("/etc/krb5/user/7/client.keytab", O_RDONLY) = -1 ENOENT (No such file or directory)
    cupds.3090:keyctl(KEYCTL_GET_PERSISTENT, 7, KEY_SPEC_PROCESS_KEYRING) = -1 EOPNOTSUPP (Operation not supported)
    cupds.3090:keyctl(KEYCTL_SEARCH, KEY_SPEC_USER_KEYRING, "keyring", "_krb", KEY_SPEC_PROCESS_KEYRING) = -1 ENOKEY (Required key not available)
    cupds.3090:add_key("keyring", "_krb", NULL, 0, KEY_SPEC_PROCESS_KEYRING) = 289500279
    cupds.3090:keyctl(KEYCTL_LINK, 289500279, KEY_SPEC_USER_KEYRING) = 0
    cupds.3090:keyctl(KEYCTL_SEARCH, 289500279, "user", "krb_ccache:primary", 0) = -1 ENOKEY (Required key not available)
    cupds.3090:add_key("user", "krb_ccache:primary", "\0\0\0\1\0\0\0\0017", 9, 289500279) = 324358986
    cupds.3090:keyctl(KEYCTL_READ, 289500279, NULL, 0) = 4
    cupds.3090:keyctl(KEYCTL_READ, 289500279, "JSU\23", 4) = 4
    cupds.3090:keyctl(KEYCTL_SEARCH, 289500279, "keyring", "7", 0) = -1 ENOKEY (Required key not available)
    cupds.3090:keyctl(KEYCTL_DESCRIBE, 324358986, NULL, 0) = 37
    cupds.3090:keyctl(KEYCTL_DESCRIBE, 324358986, "user;7;7;3f010000;krb_ccache:pri"..., 37) = 37
    cupds.3091:open("/lib/x86_64-linux-gnu/libkeyutils.so.1", O_RDONLY|O_CLOEXEC) = 6
    cupds.3091:read(7, " /key\n      4 index exch .knowng"..., 4096) = 4096
    cupds.3091:read(7, "params, key_lo, key_hi, value, f"..., 4096) = 4096

as  you can see cups exec is called with -u 7  (lp) and le bucnh of keyctl calls are trying to get the a credential cache  for lp (the calls to keyctl) which doesn't exist.

**Comment by michaelrsweet** [comment]
OK, that's the problem. The IPP backend cannot have world read/execute permissions and still work with Kerberos...

Do this:

    chmod 700 /usr/lib/cups/backend/ipp

and the problem should resolve itself.

**Comment by kenshin33** [comment]
that is weired it is an out of the box debian installation!  (gentoo's  ipp backend  has 700)

Thanks. it does indeed run as root now. still not out of woods though. seteuid() in the ipp back end is not executed, i'll need to investigate why!

**Comment by kenshin33** [comment]
stopped the ipp process when started by cupds  this a dump if it's environment :

     #strings /proc/32579/environ 
     CUPS_CACHEDIR=/var/cache/cups
     CUPS_DATADIR=/usr/share/cups
     CUPS_DOCROOT=/usr/share/cups/doc-root
     CUPS_FONTPATH=/usr/share/cups/fonts
     CUPS_REQUESTROOT=/var/spool/cups
     CUPS_SERVERBIN=/usr/lib/cups
     CUPS_SERVERROOT=/etc/cups
     CUPS_STATEDIR=/var/run/cups
     HOME=/var/spool/cups/tmp
     PATH=/usr/lib/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin
     SERVER_ADMIN=root@client
     SOFTWARE=CUPS/2.2.1
     TMPDIR=/var/spool/cups/tmp
     USER=root
     CUPS_MAX_MESSAGE=2047
     CUPS_SERVER=/var/run/cups/cups.sock
     CUPS_ENCRYPTION=IfRequested
     IPP_PORT=631
     CHARSET=utf-8
     LANG=en_CA.UTF-8
     PPD=/etc/cups/ppd/printer.ppd
     RIP_MAX_CACHE=128m
     CONTENT_TYPE=text/plain
     DEVICE_URI=ipps://server/printers/printer
     PRINTER_INFO=printer
     PRINTER_LOCATION=
     PRINTER=hp2248
     PRINTER_STATE_REASONS=none
     CUPS_FILETYPE=document
     FINAL_CONTENT_TYPE=application/vnd.cups-raster
     AUTH_INFO_REQUIRED=negotiate
     AUTH_USERNAME=user
     AUTH_PASSWORD=
     AUTH_UID=9629
    
seems AUTH_PASSWORD= is the culprit.

```C
360   if (!getuid() && (value = getenv("AUTH_UID")) != NULL &&
361       !getenv("AUTH_PASSWORD"))
362   {
363     uid_t   uid = (uid_t)atoi(value);
364                     /* User ID */
 ```

**Comment by michaelrsweet** [comment]
@kenshin33 What is the value of AuthInfoRequired in the /etc/cups/printers.conf file? It sounds like it is still set to username,password instead of negotiate...

**Comment by kenshin33** [comment]
it is "AuthInfoRequired negotiate". It is what is wrtitten in the file as of now .. I'll have to test again.

**Comment by michaelrsweet** [comment]
Hmm, well we can change this to ignore AUTH_PASSWORD if AUTH_INFO_REQUIRED is negotiate and AUTH_UID is set...

Moving to 2.2.x milestone, will apply to 2.2.x and 2.3.

**Comment by kenshin33** [comment]
Good, 
thank you. I'll be more than happy to test !

**Comment by michaelrsweet** [comment]
[master 0fea18126] Fix Kerberized IPP printing (Issue #5233)

[branch-2.2 91f56aafb] Fix Kerberized IPP printing (Issue #5233)

**Comment by kenshin33** [comment]
Tested it works. But would it make diffrence to use setuid  instead of seteuid ???

**Comment by michaelrsweet** [comment]
setuid is not reversible, while seteuid *is*. I don't know whether it matters in this case but unless you have problems I'll leave things as-is...

**Comment by kenshin33** [comment]
it can cause trouble for finding the ticket cache. Since there's no way (that I know of) to pass env vrariables (fromt the user) sessions  (KRB5CCNAME, to be precise), the kerberos library will use what ever is the default, which is UID based not EUID (unless told otherwise).

**Comment by michaelrsweet** [comment]
Hmm, we'll need to look into that some more. I did some testing and using setuid will not work because the backend won't be able to read the spool (document) files...

**Comment by michaelrsweet** [comment]
... and if it *did* work then the Kerberos code must be using the EUID... Will try to confirm...

**Comment by kenshin33** [comment]
It did b/c I played around with the ticket cache file  (for example cp /tmp/krb5cc_1234 /tmp/krb5cc_0, where 12345 is my uid).
I did rebuild the backend with setuid instead of seteuid and it worked.  the backend was able to read the file b/c the guid is 7 (lp) and the files are (640) in the spool directory.

**Comment by michaelrsweet** [comment]
Ah, right, wasn't thinking of that but of course we already run the filters as non-root.

[master 32987439c] Use setuid for Kerberized IPP printing (Issue #5233)

[branch-2.2 c59948f6f] Use setuid for Kerberized IPP printing (Issue #5233)
