### ISSUE TITLE
"Filter Failed" when using ghostscript 9.23-3

### ISSUE THREAD

**Issue by tomeaton17** [apple/cups#5392]
# Error
The 9.23-3 update to ghostscript has caused "Filter failed" to appear on all print jobs.

Looking at the error log below
```
D [01/Sep/2018:11:43:27 +0100] [Job 34] Error: /invalidfileaccess in --run--
D [01/Sep/2018:11:43:27 +0100] [Job 34] Operand stack:
D [01/Sep/2018:11:43:27 +0100] [Job 34] true   (/var/spool/cups/tmp/gs_ohd8WB)
D [01/Sep/2018:11:43:27 +0100] [Job 34] Execution stack:
D [01/Sep/2018:11:43:27 +0100] [Job 34] %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2015   2   3   %oparray_pop   2014   2   3   %oparray_pop   1998   2   3   %oparray_pop
D [01/Sep/2018:11:43:27 +0100] [Job 34] Dictionary stack:
D [01/Sep/2018:11:43:27 +0100] [Job 34] --dict:999/1684(ro)(G)--   --dict:1/20(G)--   --dict:78/200(L)--
D [01/Sep/2018:11:43:27 +0100] [Job 34] Current allocation mode is local
D [01/Sep/2018:11:43:27 +0100] [Job 34] GPL Ghostscript 9.23: Unrecoverable error, exit code 1
D [01/Sep/2018:11:43:27 +0100] [Job 34] Rendering completed
D [01/Sep/2018:11:43:27 +0100] [Job 34] Set job-printer-state-message to "Rendering completed", current level=INFO
D [01/Sep/2018:11:43:27 +0100] [Job 34] PID 6376 (/usr/lib/cups/filter/gstoraster) stopped with status 1.
D [01/Sep/2018:11:43:27 +0100] [Job 34] Hint: Try setting the LogLevel to "debug" to find out more.
D [01/Sep/2018:11:43:27 +0100] [Job 34] PID 6377 (/usr/lib/cups/filter/hpcups) exited with no errors.
D [01/Sep/2018:11:43:27 +0100] [Job 34] ready to print
D [01/Sep/2018:11:43:27 +0100] [Job 34] PID 6378 (/usr/lib/cups/backend/hp) exited with no errors.
D [01/Sep/2018:11:43:27 +0100] [Job 34] End of messages
D [01/Sep/2018:11:43:27 +0100] [Job 34] printer-state=3(idle)
D [01/Sep/2018:11:43:27 +0100] [Job 34] printer-state-message="ready to print"
D [01/Sep/2018:11:43:27 +0100] [Job 34] printer-state-reasons=none
```
It can be seen that the error is `Error: /invalidfileaccess in --run--`. 

# Potential cause
I believe this error to be the cause of this [commit](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=a054156d425b4dbdaaa9fda4b5f1182b27598c2b;hp=0d3901189f245232f0161addf215d7268c4d05a3).  The new patch checks the environment variables `TMPDIR`, `TEMP` and `TMP` to see if they contain the CUPS temp folder. At the moment they do not, which causes the error.

# Fix
Make CUPS set of on these environment variables to include the CUPS temp folder.

You can contact ghostscript on the #ghostscript channel on the freenode irc network. 

(I am not associated with ghostscript in anyway).

**Comment by michaelrsweet** [comment]
Um, CUPS absolutely does set TMPDIR, which is why you see the /var/spool/cups/tmp path. The questions should probably be:

1. Does that directory exist on your system?

2. Are there any FreeBSD patches applied to the standard CUPS sources that change whether cupsd creates this directory on startup, as needed.

**Comment by tomeaton17** [comment]
1. Yes, `/var/spool/cups/tmp` exists.
2. The patches used can be found here https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/cups

This is a problem with other Arch Linux users when using ghostscript 9.23-3

**Comment by chris-liddell** [comment]
I believe I know what what the problem is, and I have a solution, I just need to get it reviewed before I can push it. That should happen on Monday - I will update here when I know.

**Comment by chris-liddell** [comment]
If the problem is what I believe it is, then the following commit should resolve it:
http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=150c8f69646b

Apologies for the breakage - I was mislead by a *badly* incorrect comment in the code I had changed.

**Comment by michaelrsweet** [comment]
Thanks, Chris!

**Comment by FredBezies** [comment]
Sorry to be annoying, but it is still broken with hplip 3.18.6 compiled with Ghostscript 9.24.
