### ISSUE TITLE
HPLIP build with ghostscript 9.24 is broken.

### ISSUE THREAD

**Issue by FredBezies** [apple/cups#5394]
Hello. 

This is a followup of bug #5392 ; I'm on Archlinux and when I tried to print a document with HPLIP build with ghostscript 9.24.

I noticed printing is still broken with the same error: "Filter failed". I had to downgrade to ghostscript 9.23 and hold it to be able to print any document.

Some technical infos:

HPLIP 3.18.6 (3.18.7 is blocked for now on Archlinux)
Ghostscript 9.24

**Comment by FredBezies** [comment]
Ok. But which ghostscript command line?

**Comment by chris-liddell** [comment]
On 04/09/18 15:13, FredBezies wrote:
> Ok. But which ghostscript command line?

The one that triggers the invalidaccess error.

Chris

**Comment by FredBezies** [comment]
Tried to launch a print test from Cups web interface. Here is the output when I have Ghostscript 9.24 installed:

```
D [04/Sep/2018:16:22:35 +0200] [Job 53] | ./base/gsicc_manage.c:1990: gsicc_set_device_profile(): Error in device profiles
D [04/Sep/2018:16:22:35 +0200] [Job 53] Unrecoverable error: rangecheck in .putdeviceprops
D [04/Sep/2018:16:22:35 +0200] [Job 53] Operand stack:
D [04/Sep/2018:16:22:35 +0200] [Job 53] true
E [04/Sep/2018:16:23:57 +0200] [Job 54] Job stopped due to filter errors; please consult the error_log file for details.
D [04/Sep/2018:16:23:57 +0200] [Job 54] The following messages were recorded from 16:23:57 to 16:23:57
D [04/Sep/2018:16:23:57 +0200] [Job 54] Applying default options...
D [04/Sep/2018:16:23:57 +0200] [Job 54] Adding start banner page "none".
D [04/Sep/2018:16:23:57 +0200] [Job 54] Adding end banner page "none".
D [04/Sep/2018:16:23:57 +0200] [Job 54] File of type application/vnd.cups-pdf-banner queued by "root".
D [04/Sep/2018:16:23:57 +0200] [Job 54] hold_until=0
D [04/Sep/2018:16:23:57 +0200] [Job 54] Queued on "HP_DeskJet_2130_series" by "root".
D [04/Sep/2018:16:23:57 +0200] [Job 54] time-at-processing=1536071037
D [04/Sep/2018:16:23:57 +0200] [Job 54] 4 filters for job:
D [04/Sep/2018:16:23:57 +0200] [Job 54] bannertopdf (application/vnd.cups-pdf-banner to application/pdf, cost 32)
D [04/Sep/2018:16:23:57 +0200] [Job 54] pdftopdf (application/pdf to application/vnd.cups-pdf, cost 66)
D [04/Sep/2018:16:23:57 +0200] [Job 54] gstoraster (application/vnd.cups-pdf to application/vnd.cups-raster, cost 99)
D [04/Sep/2018:16:23:57 +0200] [Job 54] hpcups (application/vnd.cups-raster to printer/HP_DeskJet_2130_series, cost 0)
D [04/Sep/2018:16:23:57 +0200] [Job 54] job-sheets=none,none
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[0]="HP_DeskJet_2130_series"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[1]="54"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[2]="root"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[3]="Test Page"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[4]="1"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[5]="job-uuid=urn:uuid:c4aae755-9878-35c2-6f99-22e4a9f8487b job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1536071037 time-at-processing=1536071037"
D [04/Sep/2018:16:23:57 +0200] [Job 54] argv[6]="/var/spool/cups/d00054-001"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[0]="CUPS_CACHEDIR=/var/cache/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[1]="CUPS_DATADIR=/usr/share/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[2]="CUPS_DOCROOT=/usr/share/cups/doc"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[3]="CUPS_FONTPATH=/usr/share/cups/fonts"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[4]="CUPS_REQUESTROOT=/var/spool/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[5]="CUPS_SERVERBIN=/usr/lib/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[6]="CUPS_SERVERROOT=/etc/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[7]="CUPS_STATEDIR=/run/cups"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[8]="HOME=/var/spool/cups/tmp"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[9]="PATH=/usr/lib/cups/filter:/usr/bin:/usr/bin:/bin:/usr/bin"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[10]="SERVER_ADMIN=root@fredo-arch-mate"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[11]="SOFTWARE=CUPS/2.2.8"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[12]="TMPDIR=/var/spool/cups/tmp"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[13]="USER=root"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[14]="CUPS_MAX_MESSAGE=2047"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[15]="CUPS_SERVER=/run/cups/cups.sock"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[16]="CUPS_ENCRYPTION=IfRequested"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[17]="IPP_PORT=631"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[18]="CHARSET=utf-8"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[19]="LANG=fr.UTF-8"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[20]="PPD=/etc/cups/ppd/HP_DeskJet_2130_series.ppd"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[21]="RIP_MAX_CACHE=128m"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[22]="CONTENT_TYPE=application/vnd.cups-pdf-banner"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[23]="DEVICE_URI=usb://HP/DeskJet%202130%20series?serial=CN676471PY067S&interface=1"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[24]="PRINTER_INFO=HP DeskJet 2130 series"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[25]="PRINTER_LOCATION="
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[26]="PRINTER=HP_DeskJet_2130_series"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[27]="PRINTER_STATE_REASONS=none"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[28]="CUPS_FILETYPE=document"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[29]="FINAL_CONTENT_TYPE=application/vnd.cups-raster"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[30]="AUTH_I****"
D [04/Sep/2018:16:23:57 +0200] [Job 54] Started filter /usr/lib/cups/filter/bannertopdf (PID 3917)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Started filter /usr/lib/cups/filter/pdftopdf (PID 3918)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Started filter /usr/lib/cups/filter/gstoraster (PID 3919)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Started filter /usr/lib/cups/filter/hpcups (PID 3920)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Started backend /usr/lib/cups/backend/usb (PID 3921)
D [04/Sep/2018:16:23:57 +0200] [Job 54] PDF template file doesn\'t have form. It\'s okay.
D [04/Sep/2018:16:23:57 +0200] [Job 54] pdftopdf: Last filter determined by the PPD: hpcups; FINAL_CONTENT_TYPE: application/vnd.cups-raster => pdftopdf will not log pages in page_log.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Loading USB quirks from \"/usr/share/cups/usb\".
D [04/Sep/2018:16:23:57 +0200] [Job 54] PID 3917 (/usr/lib/cups/filter/bannertopdf) exited with no errors.
D [04/Sep/2018:16:23:57 +0200] [Job 54] OUTFORMAT=\"(null)\", so output format will be CUPS/PWG Raster
D [04/Sep/2018:16:23:57 +0200] [Job 54] Loaded 89 quirks.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Printing on printer with URI: usb://HP/DeskJet%202130%20series?serial=CN676471PY067S&interface=1
D [04/Sep/2018:16:23:57 +0200] [Job 54] Color Manager: Calibration Mode/Off
D [04/Sep/2018:16:23:57 +0200] [Job 54] PID 3918 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
D [04/Sep/2018:16:23:57 +0200] [Job 54] libusb_get_device_list=10
D [04/Sep/2018:16:23:57 +0200] [Job 54] STATE: +connecting-to-device
D [04/Sep/2018:16:23:57 +0200] [Job 54] Calling FindDeviceById(cups-HP_DeskJet_2130_series)
D [04/Sep/2018:16:23:57 +0200] [Job 54] STATE: -connecting-to-device
D [04/Sep/2018:16:23:57 +0200] [Job 54] Found device /org/freedesktop/ColorManager/devices/cups_HP_DeskJet_2130_series
D [04/Sep/2018:16:23:57 +0200] [Job 54] Calling org.freedesktop.ColorManager.Device.Get(ProfilingInhibitors)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Calling FindDeviceById(cups-HP_DeskJet_2130_series)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Printer found with device ID: MFG:HP;MDL:DeskJet 2130 series;CMD:PCL3GUI,PJL,Automatic,DW-PCL,DESKJET,DYN;CLS:PRINTER;DES:F5S40B;CID:HPDeskjet_P976D;LEDMDIS:USB#FF#CC#00,USB#07#01#02,USB#FF#04#01;SN:CN676471PY067S;S:038000C480a00001002c2400050c140003c;Z:05000008000008,12000,17000000000000,181; Device URI: usb://HP/DeskJet%202130%20series?serial=CN676471PY067S&interface=1
D [04/Sep/2018:16:23:57 +0200] [Job 54] Device protocol: 2
D [04/Sep/2018:16:23:57 +0200] [Job 54] Sending data to printer.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Set job-printer-state-message to "Sending data to printer.", current level=INFO
D [04/Sep/2018:16:23:57 +0200] [Job 54] Found device /org/freedesktop/ColorManager/devices/cups_HP_DeskJet_2130_series
D [04/Sep/2018:16:23:57 +0200] [Job 54] Calling GetProfileForQualifiers(RGB.Plain....)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Found profile /org/freedesktop/ColorManager/profiles/HP_DeskJet_2130_series_RGB__
D [04/Sep/2018:16:23:57 +0200] [Job 54] Calling org.freedesktop.ColorManager.Profile.Get(Filename)
D [04/Sep/2018:16:23:57 +0200] [Job 54] Use profile filename: \'\'
D [04/Sep/2018:16:23:57 +0200] [Job 54] Color Manager: ICC Profile: 
D [04/Sep/2018:16:23:57 +0200] [Job 54] Ghostscript using Any-Part-of-Pixel method to fill paths.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Ghostscript command line: gs -dQUIET -dPARANOIDSAFER -dNOPAUSE -dBATCH -dNOINTERPOLATE -dNOMEDIAATTRS -dShowAcroForm -sstdout=%stderr -sOutputFile=%stdout -sDEVICE=cups -sOutputType=0 -r600x600 -dMediaPosition=1 -dDEVICEWIDTHPOINTS=595 -dDEVICEHEIGHTPOINTS=841 -dcupsBitsPerColor=8 -dcupsColorOrder=0 -dcupsColorSpace=17 -dcupsInteger0=26 -scupsPageSizeName=A4 -I/usr/share/cups/fonts -c \'<</.HWMargins[8.400000 41.040001 8.400024 8.400024] /Margins[0 0]>>setpagedevice\' -f -_
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[0]=\"CUPS_CACHEDIR=/var/cache/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[1]=\"CUPS_DATADIR=/usr/share/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[2]=\"CUPS_DOCROOT=/usr/share/cups/doc\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[3]=\"CUPS_FONTPATH=/usr/share/cups/fonts\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[4]=\"CUPS_REQUESTROOT=/var/spool/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[5]=\"CUPS_SERVERBIN=/usr/lib/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[6]=\"CUPS_SERVERROOT=/etc/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[7]=\"CUPS_STATEDIR=/run/cups\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[8]=\"HOME=/var/spool/cups/tmp\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[9]=\"PATH=/usr/lib/cups/filter:/usr/bin:/usr/bin:/bin:/usr/bin\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[10]=\"SERVER_ADMIN=root@fredo-arch-mate\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[11]=\"SOFTWARE=CUPS/2.2.8\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[12]=\"TMPDIR=/var/spool/cups/tmp\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[13]=\"USER=root\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[14]=\"CUPS_MAX_MESSAGE=2047\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[15]=\"CUPS_SERVER=/run/cups/cups.sock\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[16]=\"CUPS_ENCRYPTION=IfRequested\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[17]=\"IPP_PORT=631\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[18]=\"CHARSET=utf-8\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[19]=\"LANG=fr.UTF-8\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[20]=\"PPD=/etc/cups/ppd/HP_DeskJet_2130_series.ppd\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[21]=\"RIP_MAX_CACHE=128m\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[22]=\"CONTENT_TYPE=application/vnd.cups-pdf-banner\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[23]=\"DEVICE_URI=usb://HP/DeskJet%202130%20series?serial=CN676471PY067S&interface=1\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[24]=\"PRINTER_INFO=HP DeskJet 2130 series\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[25]=\"PRINTER_LOCATION=\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[26]=\"PRINTER=HP_DeskJet_2130_series\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[27]=\"PRINTER_STATE_REASONS=none\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[28]=\"CUPS_FILETYPE=document\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[29]=\"FINAL_CONTENT_TYPE=application/vnd.cups-raster\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] envp[30]=\"AUTH_INFO_REQUIRED=none\"
D [04/Sep/2018:16:23:57 +0200] [Job 54] | ./base/gsicc_manage.c:1863: gsicc_verify_device_profiles(): Mismatch of ICC profiles and device color model
D [04/Sep/2018:16:23:57 +0200] [Job 54] | ./base/gsicc_manage.c:1990: gsicc_set_device_profile(): Error in device profiles
D [04/Sep/2018:16:23:57 +0200] [Job 54] Unrecoverable error: rangecheck in .putdeviceprops
D [04/Sep/2018:16:23:57 +0200] [Job 54] Operand stack:
D [04/Sep/2018:16:23:57 +0200] [Job 54] true
D [04/Sep/2018:16:23:57 +0200] [Job 54] PID 3919 (/usr/lib/cups/filter/gstoraster) stopped with status 1.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Hint: Try setting the LogLevel to "debug" to find out more.
D [04/Sep/2018:16:23:57 +0200] [Job 54] prnt/hpcups/HPCupsFilter.cpp 567: cupsRasterOpen failed, fd = 0
D [04/Sep/2018:16:23:57 +0200] [Job 54] Sent 0 bytes...
D [04/Sep/2018:16:23:57 +0200] [Job 54] Waiting for read thread to exit...
D [04/Sep/2018:16:23:57 +0200] [Job 54] PID 3920 (/usr/lib/cups/filter/hpcups) stopped with status 1.
D [04/Sep/2018:16:23:57 +0200] [Job 54] Hint: Try setting the LogLevel to "debug" to find out more.
D [04/Sep/2018:16:23:57 +0200] [Job 54] PID 3921 (/usr/lib/cups/backend/usb) exited with no errors.
D [04/Sep/2018:16:23:57 +0200] [Job 54] End of messages
D [04/Sep/2018:16:23:57 +0200] [Job 54] printer-state=3(idle)
D [04/Sep/2018:16:23:57 +0200] [Job 54] printer-state-message="Filter failed"
D [04/Sep/2018:16:23:57 +0200] [Job 54] printer-state-reasons=none
```

You can find this interesting,I think.

`D [04/Sep/2018:16:23:57 +0200] [Job 54] prnt/hpcups/HPCupsFilter.cpp 567: cupsRasterOpen failed, fd = 0`

**Comment by chris-liddell** [comment]
The problem is that the output ICC profile does not match the color model of the device: in this case, I *think* the device is running in RGBW mode (Red, Green, Blue, White), but is *probably* using a straight RGB ICC profile - in other words, trying to apply a three component profile to a four component device.

This is *not* related to the security fixes etc which were the source of the other problem.

And this *really* isn't my area - I really can't guess what the correct thing to do would be here.

Could I ask that you report it on:
https://bugs.ghostscript.com
And give the command line:

gs -dSAFER -dNOPAUSE -dBATCH -sOutputFile=%stdout -sDEVICE=cups \
 -dcupsColorSpace=17 -c "showpage"

as the reproducer.

Hopefully, we can then get the correct engineer to look into it.

**Comment by FredBezies** [comment]
Bug reported upstream: https://bugs.ghostscript.com/show_bug.cgi?id=699713

**Comment by 0strodamus** [comment]
Can't print with HPLIP and ghostscript 9.24 here either.

`D [04/Sep/2018:14:38:27 -0700] [Job 151] Printer make and model: HP HP Color LaserJet Pro M252c10
D [04/Sep/2018:14:38:27 -0700] [Job 151] Running command line for pstops: pstops 151 username test.pdf 1 \'HPRGBEmulation=DefaultSRGB HPGraphicsNeutralGrays=Black HPGeneralHalftone=Smooth Duplex=DuplexNoTumble PageSize=Letter HPEdgeControl=Normal InputSlot=Auto HPPhotoNeutralGrays=ProcessBlack HPTextNeutralGrays=Black HPPJLColorAsGray=no MediaType=Unspecified noHPPJLEconoMode job-uuid=urn:uuid:d74dc1fe-35ae-3104-4ec8-080a9e5e2bbf job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1536095824 time-at-processing=1536097106\'
D [04/Sep/2018:14:38:27 -0700] [Job 151] Using image rendering resolution 600 dpi
D [04/Sep/2018:14:38:27 -0700] [Job 151] Running command line for gs: gs -q -dNOPAUSE -dBATCH -dSAFER -dNOMEDIAATTRS -sDEVICE=ps2write -dShowAcroForm -sOUTPUTFILE=%stdout -dLanguageLevel=3 -r600 -dCompressFonts=false -dNoT3CCITT -dNOINTERPOLATE -c \'save pop\' -f /var/spool/cups/tmp/014165b902777
D [04/Sep/2018:14:38:27 -0700] [Job 151] Started filter gs (PID 5150)
D [04/Sep/2018:14:38:27 -0700] [Job 151] Started filter pstops (PID 5151)
D [04/Sep/2018:14:38:27 -0700] [Job 151] \033[31;01merror: Failed to create /var/spool/cups/tmp/.hplip\033[0m
D [04/Sep/2018:14:38:27 -0700] [Job 151] ./base/gsicc_manage.c:1244: gsicc_open_search(): Could not find ps_gray.icc 
D [04/Sep/2018:14:38:27 -0700] [Job 151] + ./base/gsicc_manage.c:255: gsicc_initialize_iccsmask(): failed to load gray smask profile
D [04/Sep/2018:14:38:27 -0700] [Job 151] Page = 612x792; 12,12 to 600,780
D [04/Sep/2018:14:38:27 -0700] [Job 151] slow_collate=0, slow_duplex=0, slow_order=0
D [04/Sep/2018:14:38:27 -0700] [Job 151] This document does not conform to the Adobe Document Structuring Conventions and may not print correctly.
D [04/Sep/2018:14:38:27 -0700] [Job 151] : ERROR: Error importing HPLIP modules:5143 No module named \'cupsext\'
D [04/Sep/2018:14:38:27 -0700] [Job 151] Sent 0 bytes...
D [04/Sep/2018:14:38:27 -0700] [Job 151] PID 5143 (/usr/lib/cups/filter/hpps) stopped with status 1.
D [04/Sep/2018:14:38:27 -0700] [Job 151] Hint: Try setting the LogLevel to "debug" to find out more.
D [04/Sep/2018:14:38:27 -0700] [Job 151] Waiting for read thread to exit...
D [04/Sep/2018:14:38:27 -0700] [Job 151] PID 5144 (/usr/lib/cups/backend/usb) exited with no errors.
D [04/Sep/2018:14:38:27 -0700] [Job 151] ./base/gsicc_manage.c:1244: gsicc_open_search(): Could not find default_rgb.icc 
D [04/Sep/2018:14:38:27 -0700] [Job 151] | ./base/gsicc_manage.c:2025: gsicc_set_device_profile(): cannot find device profile
D [04/Sep/2018:14:38:27 -0700] [Job 151] GPL Ghostscript 9.24: Unrecoverable error, exit code 1
D [04/Sep/2018:14:38:27 -0700] [Job 151] ./base/gsicc_manage.c:1244: gsicc_open_search(): Could not find default_gray.icc 
D [04/Sep/2018:14:38:27 -0700] [Job 151] | ./base/gsicc_manage.c:2025: gsicc_set_device_profile(): cannot find device profile
D [04/Sep/2018:14:38:27 -0700] [Job 151] PID 5150 (gs) stopped with status 1!
D [04/Sep/2018:14:38:27 -0700] [Job 151] PID 5151 (pstops) exited with no errors.
D [04/Sep/2018:14:38:27 -0700] [Job 151] PID 5142 (/usr/lib/cups/filter/pdftops) stopped with status 1.
D [04/Sep/2018:14:38:27 -0700] [Job 151] Hint: Try setting the LogLevel to "debug" to find out more.
D [04/Sep/2018:14:38:27 -0700] [Job 151] End of messages
D [04/Sep/2018:14:38:27 -0700] [Job 151] printer-state=3(idle)
D [04/Sep/2018:14:38:27 -0700] [Job 151] printer-state-message="Filter failed"
D [04/Sep/2018:14:38:27 -0700] [Job 151] printer-state-reasons=none
E [04/Sep/2018:14:43:29 -0700] [Job 151] Job stopped due to filter errors; please consult the error_log file for details.`

**Comment by chris-liddell** [comment]
I've pushed a fix for the mismatch device color space and ICC profile:
http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=bc3df0773fcc

0strodamus' problem *looks* like different: the error suggests it cannot find the ICC profiles at all.

**Comment by 0strodamus** [comment]
Yes, printing is still broken here with the patch included in Archlinux ghostscript 9.24-2.
> 0strodamus' problem looks like different: the error suggests it cannot find the ICC profiles at all.
