### ISSUE TITLE
Cannot connect to CUPS printer with basic authentication in Windows 10 1903

### ISSUE THREAD

**Issue by fangludi** [apple/cups#5600]
Hello, recently I upgrade my Win10 laptop from Win10 1809 to 1903 and suddenly find that I cannot connect to my CUPS printer anymore. When I try to add the printer manually in Control Panel, it always says "Windows couldn't connect to the printer". If I revert back to Win10 1809, it will work again. If I remove the Basic Authentication inside Get-Printer-Attributes, I can still add the printer in Win10 1903. Anyone has the same issue?

cups v2.3rc1
PS: cupsd.conf

```
LogLevel debug
MaxLogSize 1m
Port 631
Listen /run/cups/cups.sock
Browsing On
BrowseLocalProtocols dnssd
DefaultAuthType Basic
WebInterface Yes
ServerAlias cups-test
<Location />
  Order allow,deny
  Allow all
</Location>
<Location /admin>
  Order allow,deny
  Allow all
</Location>
<Location /admin/conf>
  Order allow,deny
  Allow all
</Location>
<Policy default>
  JobPrivateAccess default
  JobPrivateValues default
  SubscriptionPrivateAccess default
  SubscriptionPrivateValues default
  <Limit Get-Printer-Attributes>
    AuthType Basic
    Order allow,deny
    Allow from 10.*.*.*
  </Limit>
  <Limit Create-Job Print-Job Print-URI Validate-Job>
    AuthType Basic
    Order allow,deny
    Allow from 10.*.*.*
  </Limit>
  <Limit Send-Document Send-URI Hold-Job Release-Job Restart-Job Purge-Jobs Set-Job-Attributes Create-Job-Subscription Renew-Subscription Cancel-Subscription Get-Notifications Reprocess-Job Cancel-Current-Job Suspend-Current-Job Resume-Job Cancel-My-Jobs Close-Job CUPS-Move-Job CUPS-Get-Document>
    AuthType Basic
    Order allow,deny
    Allow from 10.*.*.*
  </Limit>
  <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default CUPS-Get-Devices>
    AuthType Basic
    Order allow,deny
    Allow from all
  </Limit>
  <Limit Pause-Printer Resume-Printer Enable-Printer Disable-Printer Pause-Printer-After-Current-Job Hold-New-Jobs Release-Held-New-Jobs Deactivate-Printer Activate-Printer Restart-Printer Shutdown-Printer Startup-Printer Promote-Job Schedule-Job-After Cancel-Jobs CUPS-Accept-Jobs CUPS-Reject-Jobs>
    AuthType Basic
    Order allow,deny
    Allow from all
  </Limit>
  <Limit CUPS-Authenticate-Job>
    Order allow,deny
    Allow from all
  </Limit>
  <Limit All>
    Order allow,deny
    Allow from 10.*.*.*
  </Limit>
</Policy>
```

PS: error_log

```
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
[19/Jun/2019:15:40:34 +0800] [Client 71] Server address is "10.92.5.15".
[19/Jun/2019:15:40:34 +0800] [Client 71] Accepted from 10.1.0.170:60428 (IPv4)
[19/Jun/2019:15:40:34 +0800] [Client 71] Waiting for request.
[19/Jun/2019:15:40:34 +0800] [Client 71] Connection now encrypted.
[19/Jun/2019:15:40:34 +0800] [Client 71] POST /printers/cups-test HTTP/1.1
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
[19/Jun/2019:15:40:34 +0800] [Client 71] Read: status=200, state=6
[19/Jun/2019:15:40:34 +0800] [Client 71] No authentication data provided.
[19/Jun/2019:15:40:34 +0800] [Client 71] 1.0 Get-Printer-Attributes 11
[19/Jun/2019:15:40:34 +0800] Get-Printer-Attributes https://cups-test:631/printers/cups-test
[19/Jun/2019:15:40:34 +0800] cupsdIsAuthorized: username=""
[19/Jun/2019:15:40:34 +0800] [Client 71] Returning HTTP Unauthorized for Get-Printer-Attributes (https://cups-test:631/printers/cups-test) from 10.1.0.170
[19/Jun/2019:15:40:34 +0800] [Client 71] cupsdSendHeader: code=401, type="text/html", auth_type=1
[19/Jun/2019:15:40:34 +0800] [Client 71] WWW-Authenticate: Basic realm=\"CUPS\"
[19/Jun/2019:15:40:34 +0800] [Client 71] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
[19/Jun/2019:15:40:34 +0800] [Client 71] Closing connection.
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
[19/Jun/2019:15:40:34 +0800] [Client 71] Waiting for socket close.
[19/Jun/2019:15:40:34 +0800] [Client 71] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
[19/Jun/2019:15:40:34 +0800] [Client 71] Closing connection.
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
[19/Jun/2019:15:40:34 +0800] [Client 72] Server address is "10.92.5.15".
[19/Jun/2019:15:40:34 +0800] [Client 72] Accepted from 10.1.0.170:60429 (IPv4)
[19/Jun/2019:15:40:34 +0800] [Client 72] Waiting for request.
[19/Jun/2019:15:40:34 +0800] [Client 72] Connection now encrypted.
[19/Jun/2019:15:40:34 +0800] [Client 72] POST /printers/cups-test HTTP/1.1
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
[19/Jun/2019:15:40:34 +0800] [Client 72] Read: status=200, state=6
[19/Jun/2019:15:40:34 +0800] [Client 72] No authentication data provided.
[19/Jun/2019:15:40:34 +0800] [Client 72] Read: status=100, state=6
[19/Jun/2019:15:40:34 +0800] [Client 72] 1.0 Get-Printer-Attributes 11
[19/Jun/2019:15:40:34 +0800] Get-Printer-Attributes https://cups-test:631/printers/cups-test
[19/Jun/2019:15:40:34 +0800] cupsdIsAuthorized: username=""
[19/Jun/2019:15:40:34 +0800] [Client 72] Returning HTTP Unauthorized for Get-Printer-Attributes (https://cups-test:631/printers/cups-test) from 10.1.0.170
[19/Jun/2019:15:40:34 +0800] [Client 72] cupsdSendHeader: code=401, type="text/html", auth_type=1
[19/Jun/2019:15:40:34 +0800] [Client 72] WWW-Authenticate: Basic realm=\"CUPS\"
[19/Jun/2019:15:40:34 +0800] [Client 72] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
[19/Jun/2019:15:40:34 +0800] [Client 72] Closing connection.
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
[19/Jun/2019:15:40:34 +0800] [Client 72] Waiting for socket close.
[19/Jun/2019:15:40:34 +0800] [Client 72] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
[19/Jun/2019:15:40:34 +0800] [Client 72] Closing connection.
[19/Jun/2019:15:40:34 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
```

**Comment by seanliu96** [comment]
I have the same problem!

**Comment by michaelrsweet** [comment]
Enabling authentication for the Get-Printer-Attributes operation (which is not defined to support it in the IPP specs) will cause clients to break (not just Windows).

**Comment by raffis** [comment]
@michaelrsweet We have the same problem here after some users upgraded to 1903. We also had Get-Printer-Attributes enabled for authentication but if I remove it from auth Windows 10 1903 does not prompt for credentials and the problem occurs later at Print-Job:

```
D [05/Jul/2019:14:32:43 +0200] Print-Job https://fqdn:631/printers/name
D [05/Jul/2019:14:32:43 +0200] [Job ???] Auto-typing file...
I [05/Jul/2019:14:32:43 +0200] [Job ???] Request file type is application/octet-stream.
D [05/Jul/2019:14:32:43 +0200] cupsdIsAuthorized: username=""
D [05/Jul/2019:14:32:43 +0200] [Client 355] Returning HTTP Unauthorized for Print-Job (https://fqdn:631/printers/name) from 10.242.2.8
D [05/Jul/2019:14:32:43 +0200] [Client 355] cupsdSendHeader: code=401, type="text/html", auth_type=1
D [05/Jul/2019:14:32:44 +0200] [Client 355] WWW-Authenticate: Basic realm=\"CUPS\"
D [05/Jul/2019:14:32:44 +0200] [Client 347] POST /printers/name HTTP/1.1
D [05/Jul/2019:14:32:44 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [05/Jul/2019:14:32:44 +0200] [Client 347] Read: status=200
D [05/Jul/2019:14:32:44 +0200] [Client 347] No authentication data provided.
D [05/Jul/2019:14:32:44 +0200] [Client 355] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [05/Jul/2019:14:32:44 +0200] [Client 355] Closing connection.
D [05/Jul/2019:14:32:44 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
```

It works on my linux after removing Get-Printer-Attributes from authentication. Linux prompts for credentials as soon as Print-Job gets triggered. But Windows build 1903 does not prompt for authentication and therefore no credentials will be sent along and cups responds with a 401.

Before the windows upgrade it worked like a charm (even tough this may have been configured against ipp specs.)

So the question is, why does the 1903 build not request user credentials? Is it a windows bug in 1903 or/and something cups can fix? @fangludi does it work in your case? Like you said adding is no problem but as soon as a new job gets posted windows does not send any credentials.

**Comment by raffis** [comment]
@michaelrsweet I am very sorry to still bother you, any news on this?

**Comment by michaelrsweet** [comment]
@raffis No, you really need to contact Microsoft to get this fixed. This isn't a CUPS issue, it is a Windows update issue causing a regression.

**Comment by manuelfhp** [comment]
I have the same problem.
I can print in OSX , but Windows 10 update 1903 I'm not able even to install IPP printer with basic authentication. I think it's a windows bug

**Comment by raffis** [comment]
Yes I think that too just wasn't sure if it's be possible to solve this on the cups server.
I have filed a windows bug report.

**Comment by TheWirefox** [comment]
I can confirm the issue for clients using Windows with a version higher 1803. Since I couldn't find anything in the changelogs regarding ipp or something else I also think it's a bug in the latest windowsupdate.

For us it worked to allow all clients to access "Get-Printer-Attributes" and to grant access to the <Location /> for all users without any authentification in cupsd.conf so we could at least add the printer to the client. In a second step, go to Control Panel -> Printers, right click on the printer -> Printer Properties -> Ports -> choose appropriate port and click configure to enter the credentials in the upcoming window.

HTH.

**Comment by raffis** [comment]
> For us it worked to allow all clients to access "Get-Printer-Attributes" and to grant access to the for all users without any authentification in cupsd.conf so we could at least add the printer to the client. In a second step, go to Control Panel -> Printers, right click on the printer -> Printer Properties -> Ports -> choose appropriate port and click configure to enter the credentials in the upcoming window.

I have no response from Microsoft so far, but this workaround is excellent news, appreciate your post @TheWirefox .

**Comment by manuelfhp** [comment]
I tried in windows build 1909 and the problem is happening too.

**Comment by orbisunom** [comment]
Hello guys just try this 
https://192.168.0.108:631/printers/Canon_iP2700_series
Instead of https:
use http only
it's working i try it already with latest windows

**Comment by manuelfhp** [comment]
> Hello guys just try this
> https://192.168.0.108:631/printers/Canon_iP2700_series
> Instead of https:
> use http only
> it's working i try it already with latest windows

for me with latest windows version is ok . I can connect IPP printers with SSL and basic authentication correctlly.
It was a windows bug and was solved by the end of 2019.

**Comment by orbisunom** [comment]
> > Hello guys just try this
> > https://192.168.0.108:631/printers/Canon_iP2700_series
> > Instead of https:
> > use http only
> > it's working i try it already with latest windows
> 
> for me with latest windows version is ok . I can connect IPP printers with SSL and basic authentication correctlly.
> It was a windows bug and was solved by the end of 2019.

Hmmm , mine still not working i have the latest 20H2 , anyway happy it's working for you too .. because maybe I'm using orange pi as server.

**Comment by Japaanc** [comment]
Think, I found the case.
have previously working cups printer, removed trying reconnect and with no luck, "cannot connect to printer", and from another pc connecting with no issues.
**Check your pc's internet connection status. if it's "Public", set it to "Private" or "Home", disconnect/reconnect network and now it should work.**

**Comment by usvi** [comment]
Sorry but I need to leave this here. I had the problem with a recent Windows version that Windows was complaining "Windows couldn't connect to the printer" when trying to add http-printer. My problem was stupid. I was using:

http://172.16.8.150:631

Instead of the full queue name: http://172.16.8.150:631/printers/Samsung_SCX-3200_Series

I did not need to change anything. Because this is one of the top hits from google, some people probably have the same problem I have.
